### ISSUE TITLE
Issue with lines when its " enclosed

### ISSUE THREAD

**Issue by bhattkrishna19** [bahaaldine/angular-csv-import#12]
I am having issue when csv line having double quote. see below-
Id,User,Lead,Assigned to,Reports to,First name,Last name,Access,Title,Department,Source,Email,Alt email,Phone,Mobile,Fax,Blog,Linkedin,Facebook,Twitter,Born on,Do not call,Deleted at,Created at,Updated at,Background info,Skype,Subscribed users,Cf geschlecht,Cf akademischer grad,Cf kontext,Cf unternehmensbereich,Tags;

“3,8,78,,,AMit v,Public,HR-Staff Development,"""",other,abcr@svg.com,"""",3232323,"""","""",www.kkk.com,"""","""","""",,false,,2011-04-12 12:55:30 +0200,2013-12-03 16:37:02 +0100,,"""",#<Set:3232323>,female,"""",,HR,""""";

Any help will be appreciated much.

**Comment by bahaaldine** [comment]
Quick questions before : 
- Is the double at the beginning of the line a mistake ?
- For empty field my understanding is that you can either have nothing or four double quotes?

**Comment by bahaaldine** [comment]
closing this as no comment has been provided ...
