### ISSUE TITLE
Any other dependencies? 

### ISSUE THREAD

**Issue by Bana0615** [bahaaldine/angular-csv-import#14]
i get  a Error: [$parse:syntax] when i load the page....the file is being called and im adding it to my app.

is there anything other than just plain angular i need to include for this to work??

**Comment by kolchy** [comment]
Bump! Getting this error as well. Anyone?

**Comment by bahaaldine** [comment]
Strange, I don't see any error on my side.
Can you provide screenshots, stacktrace or precise scenario?
Also, do you have the same behavior when testing the eample application?
Thanks;

**Comment by kolchy** [comment]
OK - found a solution. If I use the tag like this, it errors:

```
<ng-csv-import 
		class="import"
		content="csv.content"
		header="true" 
		separator=","
		result="csv.result"></ng-csv-import>
```

Like this, it works:

```
<ng-csv-import 
		class="import"
		content="csv.content"
		header="csv.header" 
		separator="csv.separator"
		result="csv.result"></ng-csv-import>
```

**Comment by bahaaldine** [comment]
ok let me change in the doc
