### ISSUE TITLE
Hook for a progress bar

### ISSUE THREAD

**Issue by pulkitsinghal** [bahaaldine/angular-csv-import#17]
For CSV files that take anywhere from 5 to 60 seconds to parse, I want to show a progress bar. For that I need a way to hook into this module and receive data like xxx out of xxx done etc.

How can that hook/callback be accomplished? Will that be an enhancement?

**Comment by bahaaldine** [comment]
Hi, this can be indeed part of the enhancement.
I can't say when I'll do that, please feel free of sending a pull request if you have done this 
to merge with the master.

**Comment by pulkitsinghal** [comment]
Thanks @bahaaldine, I chose to go with PapaParse instead, cause its so darn fast that there isn't any need for a progress bar! Also the places in their code where I can place hooks to get a progress count for painting a progress bar (if I ever really needed to) are a lot clearer.

**Comment by Calvin1121** [comment]
@pulkitsinghal Can PapaParse be used in angular?Coz this plugin's  progress-callback doesnot work~Can u help me?

**Comment by pulkitsinghal** [comment]
Yes papaparse can be used with angular. I've seen others combine webworkers in browser and angular to get good results.
