### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by paulbhartzog** [bahaaldine/angular-csv-import#19]
Added your module via bower.
included the .js as you stated.

As of today angular-csv-import.js creates:
SyntaxError: Unexpected token {
in app.js

angular-csv-import.js.min.js works.

:-)

**Comment by bahaaldine** [comment]
Hey Paul, I've updated the bower version, can you confirm this is now fixed ?

**Comment by bahaaldine** [comment]
The demo page is using the angular.csv-import.js, so I guess this is fixed.
