### ISSUE TITLE
Parsing "," inside " " Problem

### ISSUE THREAD

**Issue by masdevid** [bahaaldine/angular-csv-import#2]
Hello, I have a problem when my clients include "," in address field. I use "," as delimiter. So, I couldn't insert a new row because "," inside the address field. 
My CSV read file result like this:

0, Name, Address
1, Devid, Working Street Indonesia
2, Devid, "Not working Street, Indonesia"

But, only row 0 and 1 are working to be parsed in JSON.

**Comment by rondog** [comment]
This seems to work for the content part, but not the JSON part. It returns an empty array. The reason being `if ( currentline.length === columnCount )` fails because the column count is defined by `content.separator` causing it to split inside a quoted string

**Comment by rondog** [comment]
changing to `var columnCount = lines[0].split(content.separator).length;` to `var columnCount = lines[0].split(new RegExp(content.separator+'(?![^"]*"(?:(?:[^"]*"){2})*[^"]*$)')).length;` fixed it for me.

**Comment by bahaaldine** [comment]
Hi rondog, you can create pull request :)
