### ISSUE TITLE
Error: $compile:nonassign Non-Assignable Expression

### ISSUE THREAD

**Issue by samirdamle** [bahaaldine/angular-csv-import#26]
I was getting this error -
https://docs.angularjs.org/error/$compile/nonassign?p0=undefined&p1=ngCsvImport

I resolved it by putting "=?" instead of just "=" in the isolate scope for headerVisible and separatorVisible since they are optional attributes. [Line 15 and 17 in angular-csv-import.js]

**Comment by bahaaldine** [comment]
Hi Samir, 

Can you create a pull request for this ?

Thanks !

**Comment by asaldivar** [comment]
@bahaaldine Can you merge #25 ? I believe it should solve this issue.

**Comment by bahaaldine** [comment]
done but need to be validated @samirdamle

**Comment by asaldivar** [comment]
thanks!
