### ISSUE TITLE
The setting the separator property to a comma is causing an error

### ISSUE THREAD

**Issue by ghost** [bahaaldine/angular-csv-import#3]
I consistently get the following error when I set the separator property to "," as is is in the readme file.

`Error: [$parse:syntax] Syntax Error: Token ',' not a primary expression at column 1 of the expression`

This is the code sample I am using:

``` html
<ng-csv-import content="csv.content"
    header="true" 
    separator=","
    result="csv.result"></ng-csv-import>
```

The plugin does seem to work besides that when the separator property is not set since csv.content and csv.result are being loaded into $scope

**Comment by forrestLyman** [comment]
Thanks for clarifying!
