### ISSUE TITLE
type return is string not json array

### ISSUE THREAD

**Issue by darkmanAmazigh** [bahaaldine/angular-csv-import#5]
i try to get the data to an html table, but i have error, this error says that is a string not an array

          <ul ng-repeat="item in toPrettyJSON(csv.result, 2)">
			        <li ng-repeat="(key, val) in item">{{key}}:::::: {{val}}</li>
          </ul>

when i add the "track by $index" to ng-repeat in get me letter by letter, not item by item, i I forget something?

thank you

**Comment by jackhickey** [comment]
I removed JSON.stringify from line 89 and just return result and that seems to fix this issue.

**Comment by troytreynolds** [comment]
Is there anyway that you can make that fix on bower? It is currently just one long string compared to being a JSON object. @jackhickey  was right all that needed to be changed was the return in your directive. I ask due to me using your bower and don't want to do any alterations to your code after it is installed.

**Comment by bahaaldine** [comment]
Ok, I've updated bower as well

**Comment by abkfenris** [comment]
You can add a function to your controller, like the `toPrettyJSON` in the example.

Here's what I have
```javascript
        $scope.reJSON = function (objStr) {
            //console.log("String:", objStr);
            var out = null;
            try {
                out = $parse(objStr)({});
            } catch(e) {

            }
            //console.log(out);
            return out;
        }
```
Then when I want to interact with it as JSON in the HTML
```html
<tr ng-repeat="row in reJSON(csv.result) track by $index">
```

Then I don't need to modify the bower version.
